site_name: COMP3340 Tutorials
repo_url: https://github.com/kaixuanwang2003/COMP3340-Tutorials
repo_name: COMP3340-Tutorials
site_url: https://kaixuanwang2003.github.io/COMP3340-Tutorials/
theme:
  name: material
  logo: assets/mmlab.png
  icon:
    repo: fontawesome/brands/github
extra_css:
  - stylesheets/extra.css
nav:
  - Home: index.md
  - Tutorial 1:
    - Introduction to PyTorch: intro_pytorch/intro_pytorch.md
    - Optional - Building Neural Networks with PyTorch: intro_pytorch/optional.md
  - Tutorial 2:
    - Introduction to RoboTwin: RoboTwin_1/intro_RoboTwin.md
    - Documentations: RoboTwin_1/documentations.md